name: strapi

type: 'nodejs:16'

build:
    flavor: none
variables:
    env:
        NODE_ENV: production
hooks:
    build: |
        corepack yarn --frozen-lockfile
        corepack yarn build

web:
    commands:
        start: |
            printf "\n\n\nSANITY CHECK\n\n\n"
            corepack yarn start

disk: 1024

mounts:
    'public/uploads':
        source: local
        source_path: uploads
    '/.cache':
        source: local
        source_path: cache
    '/.tmp':
        source: local
        source_path: tmp