name: strapi

type: 'nodejs:18'

build:
    flavor: none
variables:
    env:
        NODE_ENV: production
hooks:
    build: |
        corepack yarn --frozen-lockfile
        corepack yarn build

web:
    # commands:
    #     start: |
    #         printf "\n\n\nSANITY CHECK\n\n\n"
    #         corepack yarn start

    locations:
        '/':
            # Handle dynamic requests
            root: 'build'
            index: 'index.html'
            # passthru: '/index.php'
            # Disallow static files
            allow: false
            rules:
                # Allow common image files only.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true

disk: 1024

mounts:
    'public/uploads':
        source: local
        source_path: uploads
    '/.cache':
        source: local
        source_path: cache
    '/.tmp':
        source: local
        source_path: tmp