name: strapi
 
type: 'nodejs:18'
 
build:
    flavor: none

dependencies:
    nodejs: 
        yarn: "*"
variables:
    env:
        NODE_ENV: production
hooks:
    build: |
        yarn --frozen-lockfile
        yarn build
        rsync -av -R .cache/* stage
 
    deploy: |
        rsync -av stage/.cache/* .cache
 
web:
    commands:
        start: |
            printf "\n\n\nSANITY CHECK\n\n\n"
            .global/bin/yarn start

    # locations:
    #     '/':
    #         # Handle dynamic requests
    #         root: 'build'
    #         index: 
    #             - 'index.html'
    #         # Disallow static files
    #         allow: false
    #         rules:
    #             # Allow common image files only.
    #             '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
    #                 allow: true

disk: 1024

mounts:
    'public/uploads':
        source: local
        source_path: uploads
    '/.cache':
        source: local
        source_path: cache
    '/.tmp':
        source: local
        source_path: tmp