name: strapi
 
type: 'nodejs:18'
 
build:
    flavor: none

##################################################
# WITH COREPACK
##################################################
# variables:
#     env:
#         NODE_ENV: production
# hooks:
#     build: |
#         corepack yarn --frozen-lockfile
#         corepack yarn build
#         rsync -av -R .cache/* stage
 
#     deploy: |
#         rsync -av stage/.cache/* .cache
 
# web:
#     commands:
#         start: |
#             printf "\n\n\nSANITY CHECK\n\n\n"
#             .global/bin/yarn start

##################################################
# NO COREPACK
##################################################
dependencies:
    nodejs: 
        yarn: "*"
variables:
    env:
        NODE_ENV: production
hooks:
    build: |
        yarn --frozen-lockfile
        yarn build
 
web:
    commands:
        start: .global/bin/yarn start

disk: 1024

mounts:
    'public/uploads':
        source: local
        source_path: uploads
    # '/.cache':
    #     source: local
    #     source_path: cache
    '/.tmp':
        source: local
        source_path: tmp